GET /api/books
Host: localhost:8080
Accept: application/json

####

GET /api/books/1
Host: localhost:8080
Accept: application/json

####

POST /api/books
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "title": "Let us C",
    "price": 299.0,
    "author": "Yashwant Kantikar",
    "pages": 175
}