version: "3.9"

services:
  mysql8:
    image: "mysql:latest"
    container_name: mysql8-container
    environment:
      - MYSQL_ROOT_PASSWORD=Welcome#123
    volumes:
      - "mysql_data:/var/lib/mysql"

  mongodb:
    image: "mongo:latest"
    container_name: "mongodb-container"
    volumes:
      - "mongodb_data:/data/db"

  department-service:
    build: ./department-service
    container_name: "department-service-container"
    depends_on:
      - mongodb
      - eureka-service
    environment:
      - "MONGO_HOST=mongodb"
      - "MONGO_DBNAME=DEPTDB"
      - "EUREKA_HOST=eureka-service"
      - "EUREKA_PORT=8761"

  employee-service:
    build: ./employee-service
    container_name: "employee-service-container"
    depends_on:
      - mysql8
      - eureka-service
    environment:
      - "MYSQL_HOST=mysql8"
      - "MYSQL_DBNAME=EMPLOYEEDB"
      - "DEPARTMENT_SERVICE_URL=http://department-service:8080/api/departments"
      - "EUREKA_HOST=eureka-service"
      - "EUREKA_PORT=8761"

  eureka-service:
    build: ./eureka-service
    container_name: eureka-service-container
    ports:
      - "8761:8761"

  gateway-service:
    build: ./gateway-service
    depends_on:
      - eureka-service
    container_name: gateway-service-container
    ports:
      - "8080:8080"
    environment:
      - "EUREKA_HOST=eureka-service"
      - "EUREKA_PORT=8761"

volumes:
  mysql_data:
    external: true
  mongodb_data:
    external: true